### ISSUE TITLE
Verifica URL

### ISSUE THREAD

**Issue by giuseppe-santoro** [italia/onboarding.developers.italia.it#2]
Verificare che la URL inserita sia ben formata e appartenga ad un sistema noto.

Al momento si prevede di supportare:

- https://github.com/
- https://bitbucket.org/
- http://www.cloudforge.com/
- https://sourceforge.net/
- http://www.codeplex.com/
- https://code.google.com/
- https://www.codebasehq.com/
- https://about.gitlab.com/

**Comment by ruphy** [comment]
Ciao Pasquale,
direi di sì, anche code.google.com non mi sembra accetti più progetti, sbaglio?

In generale potete rifarvi a:
http://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/attachments/allegato-b-guida-alla-pubblicazione-open-source-di-software-realizzato-per-la-pa.html#individuazione-dello-strumento-di-code-hosting

per una lista abbastanza comprensiva di piattaforme che abbiamo già selezionato

**Comment by Pasquale02** [comment]
Infatti, anche google code accettava progetti fino al 2016, come si legge sul sito. Inoltre ci sono problemi anche con cloudforge: tale piattaforma non supporta la pubblicazione di progetti opensource, ed e' quindi necessaria l' iscrizione per pubblicare progetti.
